### ISSUE TITLE
Frontend Fixes

### ISSUE THREAD

**Issue by SpellBreakerZA** [301-Redirection/301-Project#105]

**Comment by SpellBreakerZA** [comment]
Desires page:
-  slider for initial value
- one then per condition group

Hero selection page:
- sort heroes alphabetically by attribute (all strength heroes in alphabetical order) 
- the x button padding of the hero icon when placed in the pool (he liked the items x button) 
- fix pop over not disappearing properly (and only one active at a time) 
- make pop over match theme of site 
- have a bucket appear when drag starts that says add to selected pool (then
  we can keep the big hero icons) 

Item selection page:
- have a horizontal display of recipe components 
- vertically align the name of the items in the column thing? 

Abilities page: 
- tool tip for ability name and ability 
- center stuff again? 
- make talent tree pickable... 

General:
- consistency of buttons, padding and themeing of the website (for example fonts of items
  And hero pages are different)

**Comment by SpellBreakerZA** [comment]
Bot Config Page:
- Create system to allow individual components to contribute to the object sent to the backend
- Ensure that the ui can be reinstated when an object comes back from the backend

Abilities page: 
- Popover for ability description and name

**Comment by vector67** [comment]
Fixed by #107
