### ISSUE TITLE
Tests for heroes component

### ISSUE THREAD

**Issue by SpellBreakerZA** [301-Redirection/301-Project#129]

**Comment by steichert** [comment]
@vector67 Would you say the tests in this component are sufficient, or must we add anything else?

**Comment by vector67** [comment]
It would be good to have a couple more tests, adding duplicate heroes shouldn't add them. Check also in the toggle pool test that the heroes get combined in the way you expect.

**Comment by SpellBreakerZA** [comment]
Fixed By #223
