### ISSUE TITLE
Get Bootstrap-tour operational

### ISSUE THREAD

**Issue by byronantak** [301-Redirection/301-Project#141]

**Comment by vector67** [comment]
This issue has been started by #147

**Comment by russelldutton** [comment]
# Alternative ideas
- [ ] Hopscotch
- [ ] Bootstrap tours

**Comment by JustinGrenfell** [comment]
https://www.designernews.co/stories/15273-a-list-of-product-tour-plugins-for-onboarding

**Comment by vector67** [comment]
Consider using this for alerts https://sweetalert.js.org/guides/
