### ISSUE TITLE
General Fixes

### ISSUE THREAD

**Issue by steichert** [301-Redirection/301-Project#145]
General fixes to the front end.

**Comment by vector67** [comment]
This issue needs a better description

**Comment by vector67** [comment]
@steichert

**Comment by vector67** [comment]
@steichert Please describe what you did in this issue.

**Comment by steichert** [comment]
Changes and fixes done via this issue:
- Fixed the background image to be displayed better regardless of the body height
- Added the Bot Config navbar to better resemble the Dota 2 website, and appear more visually appealing
- Updated the loading icon
- Fixed spacing issues in general such as buttons and containers
- Removed unnecessary sections (Factions and Bot Teams)
- Improved the Walkthrough page layout
- Implemented the reset functionality for the Bot Config section

**Comment by vector67** [comment]
Fixed by #152
