### ISSUE TITLE
Frontend - Saving Intial BotConfig

### ISSUE THREAD

**Issue by SpellBreakerZA** [301-Redirection/301-Project#175]
Saving multiple times on the bot config page leads to many separate bot configs being saved to the database...

**Comment by vector67** [comment]
I cannot duplicate this. Please give a set of steps to reproduce this.

**Comment by SpellBreakerZA** [comment]
Create a new bot config. Change stuff.
While(true) {
 Click save
}
Check database

**Comment by SpellBreakerZA** [comment]
Fixed #204
