### ISSUE TITLE
Frontend - Generating existing bot

### ISSUE THREAD

**Issue by SpellBreakerZA** [301-Redirection/301-Project#177]
When already existing botconfig is edited, and the bot config page is opened. Then generate button does not work, only after saving the bot does generate work. This is not good because if nothing changes the database has to utilized unnecessarily

**Comment by steichert** [comment]
@SpellBreakerZA I've fixed the Generate button on the Dashboard to download scripts, but I can't seem to recreate what you described in your comment. Everything is working fine when I click the Edit button in the dashboard, and then Generate in the Bot Config page. Were you referring to the Dashboard page as well, or just the Bot Config page?

**Comment by vector67** [comment]
This may have been fixed. @spellbreakerza please confirm.

**Comment by SpellBreakerZA** [comment]
Yes. It was fixed in pull request #204 as a result of some other changes made. However I did not think to test the generate button on the dashboard. Does that work?

**Comment by steichert** [comment]
@SpellBreakerZA Yes, the generate button on the dashboard works now.

**Comment by SpellBreakerZA** [comment]
> @SpellBreakerZA Yes, the generate button on the dashboard works now.

Works now as in after changes in a branch you are currently in?

**Comment by steichert** [comment]
> > @SpellBreakerZA Yes, the generate button on the dashboard works now.
> 
> Works now as in after changes in a branch you are currently in?

Yes, I just made the changes now in the generating-existing-bot-177 branch

**Comment by SpellBreakerZA** [comment]
A

> > > @SpellBreakerZA Yes, the generate button on the dashboard works now.
> > 
> > 
> > Works now as in after changes in a branch you are currently in?
> 
> Yes, I just made the changes now in the generating-existing-bot-177 branch

OK. I see the pull request. I will look into it now

**Comment by vector67** [comment]
@SpellBreakerZA @steichert Is this fixed now?

**Comment by steichert** [comment]
> @SpellBreakerZA @steichert Is this fixed now?

I believe so.

**Comment by vector67** [comment]
Fixed by #210
