### ISSUE TITLE
Update README.md in the git repo

### ISSUE THREAD

**Issue by SpellBreakerZA** [301-Redirection/301-Project#198]

**Comment by vector67** [comment]
Update it to say what? What are we updating it to?

**Comment by SpellBreakerZA** [comment]
To have a better description of what the system is, how to get the server started (like npm install, sequelize db:migrate) if you wanted to run it yourself etc.

Example: https://github.com/sourcegraph/sourcegraph. This is a nice and readme.md that informs the user about the system

**Comment by SpellBreakerZA** [comment]
Fixed by #221
